namespace TransportReservationSystem
{
    partial class FrmHome
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            panel1 = new Panel();
            Dashboard = new Label();
            label3 = new Label();
            label2 = new Label();
            panel1.SuspendLayout();
            SuspendLayout();
            // 
            // panel1
            // 
            panel1.BackColor = Color.AliceBlue;
            panel1.Controls.Add(Dashboard);
            panel1.Controls.Add(label3);
            panel1.Controls.Add(label2);
            panel1.Location = new Point(125, 45);
            panel1.Name = "panel1";
            panel1.Size = new Size(713, 132);
            panel1.TabIndex = 9;
            // 
            // Dashboard
            // 
            Dashboard.AutoSize = true;
            Dashboard.FlatStyle = FlatStyle.Flat;
            Dashboard.Font = new Font("Century Gothic", 27.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Dashboard.ForeColor = SystemColors.ControlDark;
            Dashboard.Location = new Point(141, 26);
            Dashboard.Name = "Dashboard";
            Dashboard.Size = new Size(215, 44);
            Dashboard.TabIndex = 1;
            Dashboard.Text = "Dashboard";
            Dashboard.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Century Gothic", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.ForeColor = SystemColors.ControlDark;
            label3.Location = new Point(150, 82);
            label3.Name = "label3";
            label3.Size = new Size(212, 23);
            label3.TabIndex = 3;
            label3.Text = "Generated by Team 1";
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Century Gothic", 72F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.ForeColor = Color.DarkViolet;
            label2.Location = new Point(3, 9);
            label2.Name = "label2";
            label2.Size = new Size(141, 112);
            label2.TabIndex = 2;
            label2.Text = "ITI";
            // 
            // FrmHome
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.AliceBlue;
            ClientSize = new Size(960, 613);
            Controls.Add(panel1);
            Name = "FrmHome";
            Text = "FrmHome";
            Load += FrmHome_Load;
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Panel panel1;
        private Label Dashboard;
        private Label label3;
        private Label label2;
    }
}